# .pre-commit-config.yaml

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.0 # Replace with the latest Ruff version
    hooks:
      - id: ruff
        stages: [pre-commit, pre-push]
